apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  project: default
  source:
    helm:
      releaseName: application-from-helm
    repoURL: https://github.com/sashankreddy89/argocd.git
    path: v03-argocd-app/nginx
    targetRevision: main
